server:
  port: 9001
  error:
    include-message: always

spring:
  application:
    name: customer
  datasource:
    url: jdbc:mysql://localhost:3306/customer
    username: root
    password: Victor

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

