server:
  port: 9002
  error:
    include-message: always

spring:
  application:
    name: fraud
  datasource:
    url: jdbc:mysql://localhost:3306/customer
    username: root
    password: Victor

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      serviceZone: http://localhost:8761/eureka
